server:
    port: 9090

spring:
    application:
        name: remote-service
    datasource:
        url: jdbc:mysql://docker-mysql:3306/idlb?useSSL=false
        username: root
        password: password
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        show-sql: true
        properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
                